/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShotTenderRouteImport } from './routes/shot-tender'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShotSlugRouteImport } from './routes/shot.$slug'

const ShotTenderRoute = ShotTenderRouteImport.update({
  id: '/shot-tender',
  path: '/shot-tender',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShotSlugRoute = ShotSlugRouteImport.update({
  id: '/shot/$slug',
  path: '/shot/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/results': typeof ResultsRoute
  '/shot-tender': typeof ShotTenderRoute
  '/shot/$slug': typeof ShotSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/results': typeof ResultsRoute
  '/shot-tender': typeof ShotTenderRoute
  '/shot/$slug': typeof ShotSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/results': typeof ResultsRoute
  '/shot-tender': typeof ShotTenderRoute
  '/shot/$slug': typeof ShotSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favorites' | '/results' | '/shot-tender' | '/shot/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favorites' | '/results' | '/shot-tender' | '/shot/$slug'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/results'
    | '/shot-tender'
    | '/shot/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  ResultsRoute: typeof ResultsRoute
  ShotTenderRoute: typeof ShotTenderRoute
  ShotSlugRoute: typeof ShotSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shot-tender': {
      id: '/shot-tender'
      path: '/shot-tender'
      fullPath: '/shot-tender'
      preLoaderRoute: typeof ShotTenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shot/$slug': {
      id: '/shot/$slug'
      path: '/shot/$slug'
      fullPath: '/shot/$slug'
      preLoaderRoute: typeof ShotSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  ResultsRoute: ResultsRoute,
  ShotTenderRoute: ShotTenderRoute,
  ShotSlugRoute: ShotSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
